import { SpatialProjectConfig } from "@/types/signal-gallery";

export const SIGNAL_GALLERY_PROJECTS: SpatialProjectConfig[] = [
  {
    slug: "careeros",
    sequenceNumber: "002",
    title: "CAREEROS",
    category: "AI CAREER PLATFORM",
    descriptor: "Enterprise talent vector space & human intelligence orchestration.",
    mediaSrc: "/media/projects/careeros/hero/hero_career_world_desktop.jpg",
    width: 12.8,
    height: 8.0,
    aspectRatio: 16 / 10,
    baseX: 1.8,
    baseY: 0.2,
    baseZ: -80,
    heroZ: -8,
    exitZ: 14,
    rotationY: -0.04,
    startProgress: 0.08,
    heroProgress: 0.22,
    exitProgress: 0.36,
    caseStudyAvailable: true
  },
  {
    slug: "nestiq",
    sequenceNumber: "003",
    title: "NESTIQ",
    category: "PROPERTY INTELLIGENCE",
    descriptor: "Institutional real estate search intelligence & geospatial cadastral analytics.",
    mediaSrc: "/media/projects/nestiq/interface/agent-dashboard-preview.png",
    width: 12.8,
    height: 8.0,
    aspectRatio: 16 / 10,
    baseX: -1.6,
    baseY: -0.2,
    baseZ: -90,
    heroZ: -8,
    exitZ: 14,
    rotationY: 0.04,
    startProgress: 0.26,
    heroProgress: 0.40,
    exitProgress: 0.54,
    caseStudyAvailable: true
  },
  {
    slug: "drawdown-trading",
    sequenceNumber: "004",
    title: "DRAWDOWN.TRADING",
    category: "QUANTITATIVE RISK PLATFORM",
    descriptor: "Quantitative trading analytics interface & real-time risk controls.",
    mediaSrc: "/media/projects/drawdown/interface/dashboard.png",
    width: 13.6,
    height: 8.5,
    aspectRatio: 16 / 10,
    baseX: 0.0,
    baseY: 0.1,
    baseZ: -95,
    heroZ: -7.5,
    exitZ: 14,
    rotationY: 0.0,
    startProgress: 0.44,
    heroProgress: 0.58,
    exitProgress: 0.72,
    caseStudyAvailable: true
  },
  {
    slug: "entirefm",
    sequenceNumber: "005",
    title: "ENTIREFM",
    category: "FACILITIES OPERATIONS BACKBONE",
    descriptor: "Commercial operations platform, technician dispatch routing & search architecture.",
    mediaSrc: "/media/projects/entirefm/entirefm-operational.svg",
    width: 12.8,
    height: 8.0,
    aspectRatio: 16 / 10,
    baseX: 1.4,
    baseY: -0.2,
    baseZ: -100,
    heroZ: -8,
    exitZ: 14,
    rotationY: -0.03,
    startProgress: 0.62,
    heroProgress: 0.76,
    exitProgress: 0.88,
    caseStudyAvailable: true
  },
  {
    slug: "alkota-bikes",
    sequenceNumber: "001",
    title: "ALKOTA BIKES",
    category: "PRODUCT / BRAND / DIGITAL",
    descriptor: "Bespoke digital flagship for high-performance carbon bicycles.",
    mediaSrc: "/media/projects/alkota/product/naked-carbon-hero.jpg",
    width: 16.0,
    height: 9.0,
    aspectRatio: 16 / 9,
    baseX: 0.0,
    baseY: 0.0,
    baseZ: -110,
    heroZ: -4.2,
    exitZ: -4.2,
    rotationY: 0.0,
    startProgress: 0.78,
    heroProgress: 0.92,
    exitProgress: 1.0,
    caseStudyAvailable: true
  }
];
