import { WorkWallProject } from "@/types/work-wall";

export const WORK_WALL_PROJECTS: WorkWallProject[] = [
  {
    id: "alkota",
    slug: "alkota-bikes",
    number: "001",
    title: "Alkota Bikes",
    sector: "PERFORMANCE CYCLING",
    capability: "PRODUCT / BRAND / DIGITAL",
    imagePath: "/media/projects/alkota/alkota-hero-still.webp",
    aspectRatio: "16/10",
    colStart: 1,
    colSpan: 8,
    caseStudyAvailable: true
  },
  {
    id: "careeros",
    slug: "careeros",
    number: "002",
    title: "CareerOS",
    sector: "HUMAN INTELLIGENCE",
    capability: "AI / PRODUCT / UX",
    imagePath: "/media/projects/careeros/careeros-human-still.webp",
    aspectRatio: "3/4",
    colStart: 9,
    colSpan: 4,
    caseStudyAvailable: true
  },
  {
    id: "nestiq",
    slug: "nestiq",
    number: "003",
    title: "NestIQ",
    sector: "PROPERTY INTELLIGENCE",
    capability: "SPATIAL DATA / PRODUCT",
    imagePath: "/media/projects/nestiq/nestiq-property-hero.svg",
    aspectRatio: "4/3",
    colStart: 2,
    colSpan: 5,
    caseStudyAvailable: true
  },
  {
    id: "drawdown",
    slug: "drawdown",
    number: "004",
    title: "Drawdown.Trading",
    sector: "FINANCIAL INTELLIGENCE",
    capability: "HIGH-DENSITY DATA / UX",
    imagePath: "/media/projects/drawdown/drawdown-chart-hero.svg",
    aspectRatio: "16/10",
    colStart: 7,
    colSpan: 6,
    caseStudyAvailable: true
  },
  {
    id: "entirefm",
    slug: "entirefm",
    number: "005",
    title: "EntireFM",
    sector: "FACILITIES OPERATIONS",
    capability: "CAFM / DISPATCH / WORKFLOW",
    imagePath: "/media/projects/entirefm/entirefm-workorder-hero.svg",
    aspectRatio: "16/10",
    colStart: 1,
    colSpan: 6,
    caseStudyAvailable: true
  },
  {
    id: "aesuk",
    slug: "aesuk",
    number: "006",
    title: "AESUK",
    sector: "INDUSTRIAL ENGINEERING",
    capability: "WEB / TECHNICAL SYSTEMS",
    imagePath: "/media/projects/aesuk/aesuk-hero.svg",
    aspectRatio: "4/3",
    colStart: 7,
    colSpan: 5,
    caseStudyAvailable: false
  },
  {
    id: "travis",
    slug: "travis-gps",
    number: "007",
    title: "Travis GPS",
    sector: "HARDWARE & TELEMETRY",
    capability: "DEVICE INTERFACE / IOT",
    imagePath: "/media/projects/travis/travis-hero.svg",
    aspectRatio: "1/1",
    colStart: 2,
    colSpan: 5,
    caseStudyAvailable: false
  },
  {
    id: "steward",
    slug: "steward-farming",
    number: "008",
    title: "Steward Farming",
    sector: "AGTECH & AGRONOMY",
    capability: "LAND MANAGEMENT / UX",
    imagePath: "/media/projects/steward/steward-hero.svg",
    aspectRatio: "16/10",
    colStart: 7,
    colSpan: 6,
    caseStudyAvailable: false
  },
  {
    id: "amplios",
    slug: "amplios",
    number: "009",
    title: "Amplios",
    sector: "DIGITAL PRODUCT",
    capability: "BRAND / DEVELOPMENT",
    imagePath: "/media/projects/amplios/amplios-hero.svg",
    aspectRatio: "4/3",
    colStart: 1,
    colSpan: 5,
    caseStudyAvailable: false
  },
  {
    id: "ogn",
    slug: "one-great-northern",
    number: "010",
    title: "One Great Northern",
    sector: "COMMERCIAL PROPERTY",
    capability: "BRAND & DIGITAL PLATFORM",
    imagePath: "/media/projects/ogn/ogn-wall-hero.svg",
    aspectRatio: "16/9",
    colStart: 5,
    colSpan: 8,
    caseStudyAvailable: true
  }
];
