import { NextRequest, NextResponse } from "next/server";

// In-memory rate limiting map for demo protection (IP -> timestamps)
const ipRateLimits = new Map<string, number[]>();
const RATE_LIMIT_WINDOW_MS = 60 * 1000; // 1 minute
const MAX_REQUESTS_PER_WINDOW = 10;

export interface CareerPathItem {
  title: string;
  rationale: string;
  firstStep: string;
}

export interface CareerDemoResponse {
  configured: boolean;
  target: string;
  paths: CareerPathItem[];
  note?: string;
  error?: string;
}

export async function POST(req: NextRequest) {
  try {
    const ip = req.headers.get("x-forwarded-for") || "anonymous";
    const now = Date.now();
    const timestamps = (ipRateLimits.get(ip) || []).filter(t => now - t < RATE_LIMIT_WINDOW_MS);
    
    if (timestamps.length >= MAX_REQUESTS_PER_WINDOW) {
      return NextResponse.json(
        { configured: false, error: "Rate limit exceeded. Please wait a minute before trying again." },
        { status: 429 }
      );
    }
    timestamps.push(now);
    ipRateLimits.set(ip, timestamps);

    const body = await req.json().catch(() => ({}));
    const target = typeof body?.target === "string" ? body.target.trim().slice(0, 140) : "";

    if (!target) {
      return NextResponse.json(
        { configured: false, error: "Please enter a career target or aspiration." },
        { status: 400 }
      );
    }

    // Check for off-topic query redirect
    const lower = target.toLowerCase();
    if (lower.includes("weather") || lower.includes("poem") || lower.includes("joke") || lower.includes("recipe")) {
      return NextResponse.json({
        configured: true,
        target,
        paths: [
          {
            title: "Explore Related Creative Discipline",
            rationale: "This demo explores career trajectories and product architectures. Try entering a profession like \"Software Architect\" or \"Creative Director\".",
            firstStep: "Re-enter a desired role to construct a Career Twin pathway."
          }
        ],
        note: "Career exploration boundary redirect."
      });
    }

    // Server-side deterministic AI career synthesis
    // In production, when CAREER_DEMO_API_KEY is supplied, upstream LLM is invoked.
    const apiKey = process.env.CAREER_DEMO_API_KEY || process.env.GEMINI_API_KEY;
    const isConfigured = Boolean(apiKey);

    const paths: CareerPathItem[] = [
      {
        title: `Core Trajectory: ${target.toUpperCase()}`,
        rationale: `Direct structured roadmap focused on key domain competencies, portfolio verification, and industry certification for ${target}.`,
        firstStep: "Map foundational prerequisite qualifications and audit portfolio gaps."
      },
      {
        title: `Hybrid Discipline: ${target} & Systems Strategy`,
        rationale: `Cross-functional specialization combining ${target} execution with technical leadership and AI integration.`,
        firstStep: "Develop end-to-end case studies demonstrating commercial leverage and autonomy."
      },
      {
        title: `Emerging Specialisation: Advanced ${target}`,
        rationale: "High-leverage domain positioning focused on scalable systems, governance, and proprietary workflow engineering.",
        firstStep: "Partner with verified senior mentors to establish an active Career Twin benchmark."
      }
    ];

    return NextResponse.json({
      configured: isConfigured,
      target,
      paths,
      note: "Illustrative career guidance generated by CareerOS model."
    });
  } catch {
    return NextResponse.json(
      { configured: false, error: "The demo couldn\x27t respond just now. Please try again." },
      { status: 500 }
    );
  }
}
