import type { SceneTransitionEntry } from "@/types/transitions";

export const HOMEPAGE_TRANSITIONS: SceneTransitionEntry[] = [
  {
    id: "trans-00-01",
    fromScene: "scene-00-void",
    toScene: "scene-01-precision",
    transitionType: "GEOMETRIC_TRANSFORMATION",
    outgoingAnchor: "void-center-point",
    incomingAnchor: "precision-signal-origin",
    ownershipTransferAt: 0.85,
    preloadStart: 0.70,
    cleanupStart: 1.00,
    cleanupCompleteAt: 1.00,
    reducedMotionStrategy: "static-fade",
    mobileStrategy: "instant-flow",
    debugLabel: "Void Awakening -> Signal Origin"
  },
  {
    id: "trans-01-02",
    fromScene: "scene-01-precision",
    toScene: "scene-02-signal",
    transitionType: "SHARED_ELEMENT",
    outgoingAnchor: "signal-1px-rule",
    incomingAnchor: "signal-aperture-gate",
    ownershipTransferAt: 0.88,
    preloadStart: 0.75,
    cleanupStart: 0.95,
    cleanupCompleteAt: 1.00,
    reducedMotionStrategy: "static-rule",
    mobileStrategy: "viewport-pinned",
    debugLabel: "Precision Rule -> Signal Aperture"
  },
  {
    id: "trans-02-03",
    fromScene: "scene-02-signal",
    toScene: "scene-03-alkota",
    transitionType: "SHARED_ELEMENT",
    outgoingAnchor: "gallery-alkota-poster",
    incomingAnchor: "alkota-flagship-hero",
    ownershipTransferAt: 0.92,
    preloadStart: 0.80,
    cleanupStart: 0.95,
    cleanupCompleteAt: 1.00,
    reducedMotionStrategy: "direct-hero-cut",
    mobileStrategy: "hero-dock",
    debugLabel: "Signal Alkota Tease -> Alkota Flagship Hero"
  },
  {
    id: "trans-03-04",
    fromScene: "scene-03-alkota",
    toScene: "scene-04-breath",
    transitionType: "BLACKOUT_SILENCE",
    outgoingAnchor: "alkota-reservation-exit",
    incomingAnchor: "breath-dark-void",
    ownershipTransferAt: 0.90,
    preloadStart: 0.80,
    cleanupStart: 0.95,
    cleanupCompleteAt: 1.00,
    reducedMotionStrategy: "clean-black-cut",
    mobileStrategy: "natural-break",
    debugLabel: "Alkota Climax -> The First Breath Silence"
  },
  {
    id: "trans-04-05",
    fromScene: "scene-04-breath",
    toScene: "scene-05-careeros",
    transitionType: "SEMANTIC_TRANSFORMATION",
    outgoingAnchor: "breath-principle-text",
    incomingAnchor: "careeros-portrait-frame",
    ownershipTransferAt: 0.85,
    preloadStart: 0.70,
    cleanupStart: 0.95,
    cleanupCompleteAt: 1.00,
    reducedMotionStrategy: "fade-in",
    mobileStrategy: "portrait-stack",
    debugLabel: "Breath Principle -> CareerOS Human Intelligence"
  },
  {
    id: "trans-05-06",
    fromScene: "scene-05-careeros",
    toScene: "scene-06-build",
    transitionType: "GEOMETRIC_TRANSFORMATION",
    outgoingAnchor: "careeros-graph-fragment",
    incomingAnchor: "build-blueprint-wireframe",
    ownershipTransferAt: 0.90,
    preloadStart: 0.75,
    cleanupStart: 0.95,
    cleanupCompleteAt: 1.00,
    reducedMotionStrategy: "wireframe-settle",
    mobileStrategy: "card-settle",
    debugLabel: "CareerOS Graph -> BUILD Blueprint Node"
  },
  {
    id: "trans-06-07",
    fromScene: "scene-06-build",
    toScene: "scene-07-nestiq",
    transitionType: "GEOMETRIC_TRANSFORMATION",
    outgoingAnchor: "build-interface-frame",
    incomingAnchor: "nestiq-spatial-viewport",
    ownershipTransferAt: 0.88,
    preloadStart: 0.70,
    cleanupStart: 0.95,
    cleanupCompleteAt: 1.00,
    reducedMotionStrategy: "map-fade",
    mobileStrategy: "card-transition",
    debugLabel: "BUILD Interface Frame -> NestIQ Property Matrix"
  },
  {
    id: "trans-07-08",
    fromScene: "scene-07-nestiq",
    toScene: "scene-08-search",
    transitionType: "GEOMETRIC_TRANSFORMATION",
    outgoingAnchor: "nestiq-spatial-nodes",
    incomingAnchor: "search-entity-graph",
    ownershipTransferAt: 0.90,
    preloadStart: 0.75,
    cleanupStart: 0.95,
    cleanupCompleteAt: 1.00,
    reducedMotionStrategy: "node-restructure",
    mobileStrategy: "flow-reset",
    debugLabel: "NestIQ Spatial Nodes -> SEARCH Entity Architecture"
  },
  {
    id: "trans-08-09",
    fromScene: "scene-08-search",
    toScene: "scene-09-drawdown",
    transitionType: "SEMANTIC_TRANSFORMATION",
    outgoingAnchor: "search-authority-vector",
    incomingAnchor: "drawdown-chart-curve",
    ownershipTransferAt: 0.88,
    preloadStart: 0.70,
    cleanupStart: 0.95,
    cleanupCompleteAt: 1.00,
    reducedMotionStrategy: "chart-enter",
    mobileStrategy: "chart-stack",
    debugLabel: "SEARCH Authority Vector -> Drawdown Market Curve"
  },
  {
    id: "trans-09-10",
    fromScene: "scene-09-drawdown",
    toScene: "scene-10-systems",
    transitionType: "GEOMETRIC_TRANSFORMATION",
    outgoingAnchor: "drawdown-module-grid",
    incomingAnchor: "systems-agent-circuit",
    ownershipTransferAt: 0.90,
    preloadStart: 0.75,
    cleanupStart: 0.95,
    cleanupCompleteAt: 1.00,
    reducedMotionStrategy: "circuit-fade",
    mobileStrategy: "circuit-flow",
    debugLabel: "Drawdown Density Modules -> SYSTEMS Operational Circuit"
  },
  {
    id: "trans-10-11",
    fromScene: "scene-10-systems",
    toScene: "scene-11-entirefm",
    transitionType: "SEMANTIC_TRANSFORMATION",
    outgoingAnchor: "systems-action-gate",
    incomingAnchor: "entirefm-workorder-anchor",
    ownershipTransferAt: 0.90,
    preloadStart: 0.75,
    cleanupStart: 0.95,
    cleanupCompleteAt: 1.00,
    reducedMotionStrategy: "ticket-enter",
    mobileStrategy: "workorder-stack",
    debugLabel: "SYSTEMS Action Gate -> EntireFM Work Order Hierarchy"
  },
  {
    id: "trans-11-12",
    fromScene: "scene-11-entirefm",
    toScene: "scene-12-work",
    transitionType: "NATURAL_DOCUMENT_FLOW",
    outgoingAnchor: "entirefm-final-frame",
    incomingAnchor: "work-editorial-masonry",
    ownershipTransferAt: 0.95,
    preloadStart: 0.80,
    cleanupStart: 1.00,
    cleanupCompleteAt: 1.00,
    reducedMotionStrategy: "natural-release",
    mobileStrategy: "natural-release",
    debugLabel: "EntireFM Pin Release -> Selected Work Wall (Natural Flow)"
  },
  {
    id: "trans-12-13",
    fromScene: "scene-12-work",
    toScene: "scene-13-ogn",
    transitionType: "SHARED_ELEMENT",
    outgoingAnchor: "work-ogn-portfolio-item",
    incomingAnchor: "ogn-transformation-stage",
    ownershipTransferAt: 0.92,
    preloadStart: 0.85,
    cleanupStart: 0.98,
    cleanupCompleteAt: 1.00,
    reducedMotionStrategy: "hero-dock",
    mobileStrategy: "hero-dock",
    debugLabel: "Selected Work OGN Card -> One Great Northern Transformation"
  },
  {
    id: "trans-13-14",
    fromScene: "scene-13-ogn",
    toScene: "scene-14-lab",
    transitionType: "NATURAL_DOCUMENT_FLOW",
    outgoingAnchor: "ogn-principle-statement",
    incomingAnchor: "lab-workbench-grid",
    ownershipTransferAt: 0.95,
    preloadStart: 0.80,
    cleanupStart: 1.00,
    cleanupCompleteAt: 1.00,
    reducedMotionStrategy: "natural-flow",
    mobileStrategy: "natural-flow",
    debugLabel: "OGN Principle -> Avorria Lab Playable Workbenches"
  },
  {
    id: "trans-14-15",
    fromScene: "scene-14-lab",
    toScene: "scene-15-manifesto",
    transitionType: "BLACKOUT_SILENCE",
    outgoingAnchor: "lab-footer-signal-point",
    incomingAnchor: "manifesto-quiet-void",
    ownershipTransferAt: 0.95,
    preloadStart: 0.85,
    cleanupStart: 0.98,
    cleanupCompleteAt: 1.00,
    reducedMotionStrategy: "silence-cut",
    mobileStrategy: "silence-cut",
    debugLabel: "Lab Interactive Reduction -> Manifesto Typographic Silence"
  },
  {
    id: "trans-15-16",
    fromScene: "scene-15-manifesto",
    toScene: "scene-16-proof",
    transitionType: "NATURAL_DOCUMENT_FLOW",
    outgoingAnchor: "manifesto-proof-anchor",
    incomingAnchor: "proof-intro-heading",
    ownershipTransferAt: 0.95,
    preloadStart: 0.80,
    cleanupStart: 1.00,
    cleanupCompleteAt: 1.00,
    reducedMotionStrategy: "natural-flow",
    mobileStrategy: "natural-flow",
    debugLabel: "Manifesto Conviction Climax -> Proof Evidence Ledger"
  },
  {
    id: "trans-16-17",
    fromScene: "scene-16-proof",
    toScene: "scene-17-intelligence",
    transitionType: "NATURAL_DOCUMENT_FLOW",
    outgoingAnchor: "proof-intelligence-anchor",
    incomingAnchor: "intelligence-intro-heading",
    ownershipTransferAt: 0.95,
    preloadStart: 0.80,
    cleanupStart: 1.00,
    cleanupCompleteAt: 1.00,
    reducedMotionStrategy: "natural-flow",
    mobileStrategy: "natural-flow",
    debugLabel: "Proof Evidence Ledger -> Intelligence Editorial Essays"
  },
  {
    id: "trans-17-18",
    fromScene: "scene-17-intelligence",
    toScene: "scene-18-finale",
    transitionType: "SHARED_ELEMENT",
    outgoingAnchor: "intelligence-editorial-rule",
    incomingAnchor: "finale-signal-callback",
    ownershipTransferAt: 0.90,
    preloadStart: 0.80,
    cleanupStart: 0.95,
    cleanupCompleteAt: 1.00,
    reducedMotionStrategy: "rule-transfer",
    mobileStrategy: "rule-transfer",
    debugLabel: "Intelligence Editorial Rule -> Finale Signal Line Callback"
  },
  {
    id: "trans-18-footer",
    fromScene: "scene-18-finale",
    toScene: "footer",
    transitionType: "NATURAL_DOCUMENT_FLOW",
    outgoingAnchor: "finale-actions-container",
    incomingAnchor: "global-footer-root",
    ownershipTransferAt: 0.95,
    preloadStart: 0.85,
    cleanupStart: 1.00,
    cleanupCompleteAt: 1.00,
    reducedMotionStrategy: "footer-release",
    mobileStrategy: "footer-release",
    debugLabel: "Finale Pin Release -> Global Footer Administrative Closure"
  }
];
