
const fs = require("fs");
const path = require("path");

function write(filePath, content) {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(filePath, content.trim() + "\n");
  console.log("Created: " + filePath);
}

// 1. src/types/signal-gallery.ts
write("src/types/signal-gallery.ts", [
  "export interface SpatialProjectConfig {",
  "  slug: string;",
  "  sequenceNumber: string;",
  "  title: string;",
  "  category: string;",
  "  descriptor: string;",
  "  mediaSrc: string;",
  "  width: number;",
  "  height: number;",
  "  aspectRatio: number;",
  "  baseX: number;",
  "  baseY: number;",
  "  baseZ: number;",
  "  heroZ: number;",
  "  exitZ: number;",
  "  rotationY: number;",
  "  startProgress: number;",
  "  heroProgress: number;",
  "  exitProgress: number;",
  "  caseStudyAvailable: boolean;",
  "}",
  "",
  "export interface ActiveProjectState {",
  "  index: number;",
  "  project: SpatialProjectConfig;",
  "  opacity: number;",
  "}"
].join("\n"));

// 2. src/lib/scenes/signal-gallery-config.ts
write("src/lib/scenes/signal-gallery-config.ts", [
  "import { SpatialProjectConfig } from \"@/types/signal-gallery\";",
  "",
  "export const SIGNAL_GALLERY_PROJECTS: SpatialProjectConfig[] = [",
  "  {",
  "    slug: \"careeros\",",
  "    sequenceNumber: \"002\",",
  "    title: \"CAREEROS\",",
  "    category: \"AI CAREER PLATFORM\",",
  "    descriptor: \"Enterprise talent vector space & autonomous agent workflow orchestration.\",",
  "    mediaSrc: \"/media/projects/careeros/hero/careeros-signal.svg\",",
  "    width: 12.8,",
  "    height: 8.0,",
  "    aspectRatio: 16 / 10,",
  "    baseX: 1.8,",
  "    baseY: 0.2,",
  "    baseZ: -80,",
  "    heroZ: -8,",
  "    exitZ: 14,",
  "    rotationY: -0.04,",
  "    startProgress: 0.08,",
  "    heroProgress: 0.22,",
  "    exitProgress: 0.36,",
  "    caseStudyAvailable: true",
  "  },",
  "  {",
  "    slug: \"nestiq\",",
  "    sequenceNumber: \"003\",",
  "    title: \"NESTIQ\",",
  "    category: \"PROPERTY INTELLIGENCE\",",
  "    descriptor: \"Institutional real estate search intelligence & geospatial cadastral analytics.\",",
  "    mediaSrc: \"/media/projects/nestiq/hero/nestiq-signal.svg\",",
  "    width: 12.8,",
  "    height: 8.0,",
  "    aspectRatio: 16 / 10,",
  "    baseX: -1.6,",
  "    baseY: -0.2,",
  "    baseZ: -90,",
  "    heroZ: -8,",
  "    exitZ: 14,",
  "    rotationY: 0.04,",
  "    startProgress: 0.26,",
  "    heroProgress: 0.40,",
  "    exitProgress: 0.54,",
  "    caseStudyAvailable: true",
  "  },",
  "  {",
  "    slug: \"drawdown-trading\",",
  "    sequenceNumber: \"004\",",
  "    title: \"DRAWDOWN.TRADING\",",
  "    category: \"QUANTITATIVE RISK PLATFORM\",",
  "    descriptor: \"Low-latency trading analytics interface & sub-millisecond risk controls.\",",
  "    mediaSrc: \"/media/projects/drawdown/hero/drawdown-signal.svg\",",
  "    width: 13.6,",
  "    height: 8.5,",
  "    aspectRatio: 16 / 10,",
  "    baseX: 0.0,",
  "    baseY: 0.1,",
  "    baseZ: -95,",
  "    heroZ: -7.5,",
  "    exitZ: 14,",
  "    rotationY: 0.0,",
  "    startProgress: 0.44,",
  "    heroProgress: 0.58,",
  "    exitProgress: 0.72,",
  "    caseStudyAvailable: true",
  "  },",
  "  {",
  "    slug: \"entirefm\",",
  "    sequenceNumber: \"005\",",
  "    title: \"ENTIREFM\",",
  "    category: \"FACILITIES OPERATIONS BACKBONE\",",
  "    descriptor: \"Commercial operations platform, technician dispatch routing & search architecture.\",",
  "    mediaSrc: \"/media/projects/entirefm/hero/entirefm-signal.svg\",",
  "    width: 12.8,",
  "    height: 8.0,",
  "    aspectRatio: 16 / 10,",
  "    baseX: 1.4,",
  "    baseY: -0.2,",
  "    baseZ: -100,",
  "    heroZ: -8,",
  "    exitZ: 14,",
  "    rotationY: -0.03,",
  "    startProgress: 0.62,",
  "    heroProgress: 0.76,",
  "    exitProgress: 0.88,",
  "    caseStudyAvailable: true",
  "  },",
  "  {",
  "    slug: \"alkota-bikes\",",
  "    sequenceNumber: \"006\",",
  "    title: \"ALKOTA BIKES\",",
  "    category: \"PRODUCT / BRAND / DIGITAL\",",
  "    descriptor: \"Bespoke digital flagship for titanium performance bicycles.\",",
  "    mediaSrc: \"/media/projects/alkota/hero/alkota-signal.svg\",",
  "    width: 16.0,",
  "    height: 9.0,",
  "    aspectRatio: 16 / 9,",
  "    baseX: 0.0,",
  "    baseY: 0.0,",
  "    baseZ: -110,",
  "    heroZ: -4.2,",
  "    exitZ: -4.2,",
  "    rotationY: 0.0,",
  "    startProgress: 0.78,",
  "    heroProgress: 0.92,",
  "    exitProgress: 1.0,",
  "    caseStudyAvailable: true",
  "  }",
  "];"
].join("\n"));

// 3. src/components/scenes/signal/SignalAperture.tsx
write("src/components/scenes/signal/SignalAperture.tsx", [
  "\"use client\";",
  "import React from \"react\";",
  "",
  "interface SignalApertureProps {",
  "  progress: number;",
  "  children: React.ReactNode;",
  "}",
  "",
  "export function SignalAperture({ progress, children }: SignalApertureProps) {",
  "  const apertureWidthPercent = Math.min(100, Math.max(0.05, Math.pow(progress, 1.8) * 100));",
  "  const insetHorizontal = (100 - apertureWidthPercent) / 2;",
  "",
  "  return (",
  "    <div className=\"relative w-full h-full overflow-hidden bg-avorria-black\">",
  "      <div",
  "        className=\"w-full h-full relative\"",
  "        style={{",
  "          clipPath: \"inset(0% \" + insetHorizontal + \"% 0% \" + insetHorizontal + \"%)\",",
  "          WebkitClipPath: \"inset(0% \" + insetHorizontal + \"% 0% \" + insetHorizontal + \"%)\"",
  "        }}",
  "      >",
  "        {children}",
  "      </div>",
  "",
  "      {progress < 0.95 && (",
  "        <>",
  "          <div",
  "            className=\"absolute top-0 bottom-0 w-[1px] bg-avorria-signal pointer-events-none transition-opacity duration-150\"",
  "            style={{",
  "              left: insetHorizontal + \"%\",",
  "              opacity: Math.max(0, 1 - progress * 1.5)",
  "            }}",
  "            aria-hidden=\"true\"",
  "          />",
  "          <div",
  "            className=\"absolute top-0 bottom-0 w-[1px] bg-avorria-signal pointer-events-none transition-opacity duration-150\"",
  "            style={{",
  "              right: insetHorizontal + \"%\",",
  "              opacity: Math.max(0, 1 - progress * 1.5)",
  "            }}",
  "            aria-hidden=\"true\"",
  "          />",
  "        </>",
  "      )}",
  "    </div>",
  "  );",
  "}"
].join("\n"));

// 4. src/components/scenes/signal/SignalSpatialWorld.ts
write("src/components/scenes/signal/SignalSpatialWorld.ts", [
  "import * as THREE from \"three\";",
  "import { SIGNAL_GALLERY_PROJECTS } from \"@/lib/scenes/signal-gallery-config\";",
  "",
  "export class SignalSpatialWorld {",
  "  private container: HTMLElement;",
  "  private scene: THREE.Scene;",
  "  private camera: THREE.PerspectiveCamera;",
  "  private renderer: THREE.WebGLRenderer;",
  "  private textureLoader: THREE.TextureLoader;",
  "  private projectMeshes: { mesh: THREE.Mesh; config: typeof SIGNAL_GALLERY_PROJECTS[0] }[] = [];",
  "  ",
  "  private currentProgress = 0;",
  "  private targetPointerX = 0;",
  "  private targetPointerY = 0;",
  "  private currentPointerX = 0;",
  "  private currentPointerY = 0;",
  "  private isDisposed = false;",
  "  private animationFrameId: number | null = null;",
  "",
  "  constructor(container: HTMLElement, dprCap = 1.5) {",
  "    this.container = container;",
  "    const width = container.clientWidth || window.innerWidth;",
  "    const height = container.clientHeight || window.innerHeight;",
  "",
  "    this.scene = new THREE.Scene();",
  "    this.scene.background = new THREE.Color(\"#080808\");",
  "",
  "    this.camera = new THREE.PerspectiveCamera(45, width / height, 0.1, 500);",
  "    this.camera.position.set(0, 0, 10);",
  "",
  "    this.renderer = new THREE.WebGLRenderer({",
  "      powerPreference: \"high-performance\",",
  "      antialias: true,",
  "      alpha: false",
  "    });",
  "    this.renderer.setSize(width, height);",
  "    this.renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, dprCap));",
  "    this.renderer.toneMapping = THREE.ACESFilmicToneMapping;",
  "    this.renderer.toneMappingExposure = 1.05;",
  "",
  "    this.container.appendChild(this.renderer.domElement);",
  "    this.textureLoader = new THREE.TextureLoader();",
  "",
  "    this.initProjects();",
  "",
  "    this.render = this.render.bind(this);",
  "    this.render();",
  "  }",
  "",
  "  private initProjects() {",
  "    SIGNAL_GALLERY_PROJECTS.forEach((config) => {",
  "      const geometry = new THREE.PlaneGeometry(config.width, config.height);",
  "      const texture = this.textureLoader.load(config.mediaSrc, () => {",
  "        texture.generateMipmaps = true;",
  "        texture.minFilter = THREE.LinearMipmapLinearFilter;",
  "        texture.magFilter = THREE.LinearFilter;",
  "      });",
  "",
  "      const material = new THREE.MeshBasicMaterial({",
  "        map: texture,",
  "        transparent: true,",
  "        opacity: 0.0,",
  "        side: THREE.FrontSide",
  "      });",
  "",
  "      const mesh = new THREE.Mesh(geometry, material);",
  "      mesh.position.set(config.baseX, config.baseY, config.baseZ);",
  "      mesh.rotation.y = config.rotationY;",
  "",
  "      this.scene.add(mesh);",
  "      this.projectMeshes.push({ mesh, config });",
  "    });",
  "  }",
  "",
  "  public setProgress(progress: number) {",
  "    this.currentProgress = Math.max(0, Math.min(1, progress));",
  "  }",
  "",
  "  public setPointer(x: number, y: number) {",
  "    this.targetPointerX = x;",
  "    this.targetPointerY = y;",
  "  }",
  "",
  "  public resize(width: number, height: number) {",
  "    if (this.isDisposed || !this.renderer || !this.camera) return;",
  "    this.camera.aspect = width / height;",
  "    this.camera.updateProjectionMatrix();",
  "    this.renderer.setSize(width, height);",
  "  }",
  "",
  "  private render() {",
  "    if (this.isDisposed) return;",
  "",
  "    this.currentPointerX += (this.targetPointerX - this.currentPointerX) * 0.05;",
  "    this.currentPointerY += (this.targetPointerY - this.currentPointerY) * 0.05;",
  "",
  "    this.camera.position.x = this.currentPointerX * 0.4;",
  "    this.camera.position.y = this.currentPointerY * 0.3;",
  "    this.camera.lookAt(0, 0, -30);",
  "",
  "    const p = this.currentProgress;",
  "",
  "    this.projectMeshes.forEach(({ mesh, config }) => {",
  "      const { startProgress, heroProgress, exitProgress, baseX, baseY, baseZ, heroZ, exitZ, rotationY } = config;",
  "",
  "      if (p < startProgress) {",
  "        mesh.position.set(baseX, baseY, baseZ);",
  "        (mesh.material as THREE.MeshBasicMaterial).opacity = 0;",
  "        mesh.visible = false;",
  "      } else if (p >= startProgress && p < heroProgress) {",
  "        mesh.visible = true;",
  "        const localT = (p - startProgress) / (heroProgress - startProgress);",
  "        const z = THREE.MathUtils.lerp(baseZ, heroZ, localT);",
  "        mesh.position.set(baseX, baseY, z);",
  "        (mesh.material as THREE.MeshBasicMaterial).opacity = THREE.MathUtils.lerp(0.1, 1.0, localT);",
  "        mesh.rotation.y = THREE.MathUtils.lerp(rotationY, 0, localT);",
  "      } else if (p >= heroProgress && p <= exitProgress) {",
  "        mesh.visible = true;",
  "        const localT = (p - heroProgress) / (exitProgress - heroProgress);",
  "        const z = THREE.MathUtils.lerp(heroZ, exitZ, localT);",
  "        ",
  "        if (config.slug === \"alkota-bikes\") {",
  "          mesh.position.set(0, 0, z);",
  "          (mesh.material as THREE.MeshBasicMaterial).opacity = 1.0;",
  "        } else {",
  "          const xOffset = baseX > 0 ? baseX + localT * 4 : baseX - localT * 4;",
  "          mesh.position.set(xOffset, baseY, z);",
  "          (mesh.material as THREE.MeshBasicMaterial).opacity = THREE.MathUtils.lerp(1.0, 0.0, localT * 1.5);",
  "        }",
  "      } else {",
  "        (mesh.material as THREE.MeshBasicMaterial).opacity = 0;",
  "        mesh.visible = false;",
  "      }",
  "    });",
  "",
  "    this.renderer.render(this.scene, this.camera);",
  "    this.animationFrameId = requestAnimationFrame(this.render);",
  "  }",
  "",
  "  public dispose() {",
  "    this.isDisposed = true;",
  "    if (this.animationFrameId !== null) {",
  "      cancelAnimationFrame(this.animationFrameId);",
  "    }",
  "",
  "    this.projectMeshes.forEach(({ mesh }) => {",
  "      mesh.geometry.dispose();",
  "      if (Array.isArray(mesh.material)) {",
  "        mesh.material.forEach((m) => m.dispose());",
  "      } else {",
  "        const mat = mesh.material as THREE.MeshBasicMaterial;",
  "        if (mat.map) mat.map.dispose();",
  "        mat.dispose();",
  "      }",
  "    });",
  "",
  "    this.scene.clear();",
  "    this.renderer.dispose();",
  "",
  "    if (this.renderer.domElement && this.renderer.domElement.parentNode) {",
  "      this.renderer.domElement.parentNode.removeChild(this.renderer.domElement);",
  "    }",
  "  }",
  "}"
].join("\n"));

// 5. src/components/scenes/signal/SignalCanvas.tsx
write("src/components/scenes/signal/SignalCanvas.tsx", [
  "\"use client\";",
  "import React, { useEffect, useRef } from \"react\";",
  "import { SignalSpatialWorld } from \"./SignalSpatialWorld\";",
  "import { useReducedMotion } from \"@/providers/ReducedMotionProvider\";",
  "import { useWebGLCapabilities } from \"@/providers/WebGLCapabilityProvider\";",
  "",
  "interface SignalCanvasProps {",
  "  progress: number;",
  "  onActiveProjectChange?: (index: number) => void;",
  "}",
  "",
  "export function SignalCanvas({ progress, onActiveProjectChange }: SignalCanvasProps) {",
  "  const containerRef = useRef<HTMLDivElement | null>(null);",
  "  const worldRef = useRef<SignalSpatialWorld | null>(null);",
  "  const { effectiveReducedMotion } = useReducedMotion();",
  "  const { capabilities, forceDisabled } = useWebGLCapabilities();",
  "",
  "  useEffect(() => {",
  "    if (effectiveReducedMotion || forceDisabled || !containerRef.current) return;",
  "",
  "    const world = new SignalSpatialWorld(containerRef.current, capabilities.maxDpr);",
  "    worldRef.current = world;",
  "",
  "    const onPointerMove = (e: MouseEvent) => {",
  "      const normX = (e.clientX / window.innerWidth) * 2 - 1;",
  "      const normY = -(e.clientY / window.innerHeight) * 2 + 1;",
  "      world.setPointer(normX, normY);",
  "    };",
  "",
  "    const onResize = () => {",
  "      if (containerRef.current) {",
  "        world.resize(containerRef.current.clientWidth, containerRef.current.clientHeight);",
  "      }",
  "    };",
  "",
  "    window.addEventListener(\"mousemove\", onPointerMove, { passive: true });",
  "    window.addEventListener(\"resize\", onResize);",
  "",
  "    return () => {",
  "      window.removeEventListener(\"mousemove\", onPointerMove);",
  "      window.removeEventListener(\"resize\", onResize);",
  "      world.dispose();",
  "      worldRef.current = null;",
  "    };",
  "  }, [effectiveReducedMotion, forceDisabled, capabilities.maxDpr]);",
  "",
  "  useEffect(() => {",
  "    if (worldRef.current) {",
  "      worldRef.current.setProgress(progress);",
  "    }",
  "",
  "    if (onActiveProjectChange) {",
  "      if (progress < 0.28) onActiveProjectChange(0);",
  "      else if (progress < 0.46) onActiveProjectChange(1);",
  "      else if (progress < 0.64) onActiveProjectChange(2);",
  "      else if (progress < 0.80) onActiveProjectChange(3);",
  "      else onActiveProjectChange(4);",
  "    }",
  "  }, [progress, onActiveProjectChange]);",
  "",
  "  return (",
  "    <div",
  "      ref={containerRef}",
  "      className=\"w-full h-full absolute inset-0 pointer-events-none\"",
  "      aria-hidden=\"true\"",
  "    />",
  "  );",
  "}"
].join("\n"));

// 6. src/components/scenes/signal/SignalMetadataOverlay.tsx
write("src/components/scenes/signal/SignalMetadataOverlay.tsx", [
  "import React from \"react\";",
  "import Link from \"next/link\";",
  "import { SIGNAL_GALLERY_PROJECTS } from \"@/lib/scenes/signal-gallery-config\";",
  "import { CursorTrigger } from \"@/providers/CursorContext\";",
  "",
  "interface SignalMetadataOverlayProps {",
  "  activeIndex: number;",
  "  progress: number;",
  "}",
  "",
  "export function SignalMetadataOverlay({ activeIndex, progress }: SignalMetadataOverlayProps) {",
  "  const currentProject = SIGNAL_GALLERY_PROJECTS[activeIndex] || SIGNAL_GALLERY_PROJECTS[0];",
  "  const isApertureOpen = progress > 0.1;",
  "  const isAlkotaTakeover = progress > 0.94;",
  "",
  "  if (!isApertureOpen || isAlkotaTakeover) return null;",
  "",
  "  return (",
  "    <div",
  "      className=\"absolute bottom-8 sm:bottom-12 left-6 sm:left-12 lg:left-16 z-20 pointer-events-auto max-w-lg transition-opacity duration-300\"",
  "      role=\"region\"",
  "      aria-label=\"Active Featured Project\"",
  "    >",
  "      <div className=\"flex items-center gap-3 font-mono text-[11px] uppercase tracking-widest text-avorria-quiet mb-2\">",
  "        <span className=\"text-avorria-signal\">{currentProject.sequenceNumber}</span>",
  "        <span className=\"text-avorria-line-strong\">/</span>",
  "        <span className=\"text-avorria-white\">{currentProject.category}</span>",
  "      </div>",
  "",
  "      <h3 className=\"font-display font-bold text-2xl sm:text-3xl uppercase tracking-tight text-avorria-white mb-2\">",
  "        {currentProject.title}",
  "      </h3>",
  "",
  "      <p className=\"font-mono text-xs text-avorria-muted uppercase tracking-wider mb-4 max-w-md leading-relaxed hidden sm:block\">",
  "        {currentProject.descriptor}",
  "      </p>",
  "",
  "      {currentProject.caseStudyAvailable && (",
  "        <CursorTrigger state=\"view\" label=\"VIEW\">",
  "          <Link",
  "            href={\"/work/\" + currentProject.slug}",
  "            className=\"inline-flex items-center gap-2 font-mono text-[11px] uppercase tracking-widest text-avorria-signal hover:text-avorria-white transition-colors\"",
  "          >",
  "            <span>VIEW PROJECT</span>",
  "            <span>→</span>",
  "          </Link>",
  "        </CursorTrigger>",
  "      )}",
  "    </div>",
  "  );",
  "}"
].join("\n"));

// 7. src/components/scenes/signal/AlkotaHandoffLayer.tsx
write("src/components/scenes/signal/AlkotaHandoffLayer.tsx", [
  "import React from \"react\";",
  "import Image from \"next/image\";",
  "",
  "interface AlkotaHandoffLayerProps {",
  "  opacity: number;",
  "}",
  "",
  "export function AlkotaHandoffLayer({ opacity }: AlkotaHandoffLayerProps) {",
  "  if (opacity <= 0.01) return null;",
  "",
  "  return (",
  "    <div",
  "      className=\"absolute inset-0 w-full h-full z-30 pointer-events-none transition-opacity duration-150\"",
  "      style={{ opacity }}",
  "      aria-hidden=\"true\"",
  "    >",
  "      <Image",
  "        src=\"/media/projects/alkota/hero/alkota-signal.svg\"",
  "        alt=\"Alkota Bikes Titanium Platform\"",
  "        fill",
  "        priority",
  "        className=\"object-cover\"",
  "      />",
  "    </div>",
  "  );",
  "}"
].join("\n"));

// 8. src/components/scenes/signal/SignalFallback.tsx
write("src/components/scenes/signal/SignalFallback.tsx", [
  "import React from \"react\";",
  "import Link from \"next/link\";",
  "import Image from \"next/image\";",
  "import { SIGNAL_GALLERY_PROJECTS } from \"@/lib/scenes/signal-gallery-config\";",
  "",
  "export function SignalFallback() {",
  "  return (",
  "    <div className=\"w-full min-h-screen bg-avorria-black px-6 sm:px-12 py-24 flex flex-col gap-24 max-w-[1760px] mx-auto\">",
  "      <div className=\"border-b border-avorria-line pb-8\">",
  "        <span className=\"font-mono text-xs text-avorria-signal uppercase tracking-widest\">",
  "          02 / SIGNAL",
  "        </span>",
  "        <h2 className=\"display-lg uppercase text-avorria-white mt-2\">",
  "          Selected Project Archive",
  "        </h2>",
  "      </div>",
  "",
  "      <div className=\"flex flex-col gap-32\">",
  "        {SIGNAL_GALLERY_PROJECTS.map((project) => (",
  "          <article",
  "            key={project.slug}",
  "            className=\"flex flex-col lg:flex-row gap-8 lg:gap-16 items-start border-b border-avorria-line pb-16\"",
  "          >",
  "            <div className=\"w-full lg:w-2/3 aspect-video relative overflow-hidden bg-avorria-surface border border-avorria-line\">",
  "              <Image",
  "                src={project.mediaSrc}",
  "                alt={project.title}",
  "                fill",
  "                className=\"object-cover\"",
  "              />",
  "            </div>",
  "",
  "            <div className=\"w-full lg:w-1/3 flex flex-col justify-between\">",
  "              <div>",
  "                <div className=\"font-mono text-xs text-avorria-signal uppercase tracking-widest mb-2\">",
  "                  {project.sequenceNumber} // {project.category}",
  "                </div>",
  "                <h3 className=\"font-display font-bold text-3xl uppercase tracking-tight text-avorria-white mb-4\">",
  "                  {project.title}",
  "                </h3>",
  "                <p className=\"font-body text-sm text-avorria-muted leading-relaxed mb-8\">",
  "                  {project.descriptor}",
  "                </p>",
  "              </div>",
  "",
  "              <Link",
  "                href={\"/work/\" + project.slug}",
  "                className=\"inline-flex items-center gap-2 font-mono text-xs uppercase tracking-widest text-avorria-signal hover:text-avorria-white border-b border-avorria-signal pb-1\"",
  "              >",
  "                <span>Explore Case Study</span>",
  "                <span>→</span>",
  "              </Link>",
  "            </div>",
  "          </article>",
  "        ))}",
  "      </div>",
  "    </div>",
  "  );",
  "}"
].join("\n"));

// 9. src/components/scenes/Scene02Signal.tsx
write("src/components/scenes/Scene02Signal.tsx", [
  "\"use client\";",
  "import React, { useRef, useState } from \"react\";",
  "import dynamic from \"next/dynamic\";",
  "import { useGsapContext } from \"@/lib/motion/hooks\";",
  "import { useReducedMotion } from \"@/providers/ReducedMotionProvider\";",
  "import { useWebGLCapabilities } from \"@/providers/WebGLCapabilityProvider\";",
  "import { SignalAperture } from \"./signal/SignalAperture\";",
  "import { SignalMetadataOverlay } from \"./signal/SignalMetadataOverlay\";",
  "import { AlkotaHandoffLayer } from \"./signal/AlkotaHandoffLayer\";",
  "import { SignalFallback } from \"./signal/SignalFallback\";",
  "import { getSceneConfig } from \"./registry\";",
  "",
  "const SignalCanvas = dynamic(",
  "  () => import(\"./signal/SignalCanvas\").then((mod) => mod.SignalCanvas),",
  "  { ssr: false }",
  ");",
  "",
  "export function Scene02Signal() {",
  "  const containerRef = useRef<HTMLDivElement | null>(null);",
  "  const pinnedContentRef = useRef<HTMLDivElement | null>(null);",
  "  const [scrollProgress, setScrollProgress] = useState(0);",
  "  const [activeProjectIndex, setActiveProjectIndex] = useState(0);",
  "  ",
  "  const { effectiveReducedMotion } = useReducedMotion();",
  "  const { effectiveSupported } = useWebGLCapabilities();",
  "  const config = getSceneConfig(\"scene-02-signal\")!;",
  "",
  "  useGsapContext((ctx) => {",
  "    if (effectiveReducedMotion || !effectiveSupported || !containerRef.current || !pinnedContentRef.current) return;",
  "",
  "    ctx.add(() => {",
  "      const gsap = require(\"gsap\").gsap;",
  "      gsap.to(",
  "        {},",
  "        {",
  "          scrollTrigger: {",
  "            trigger: containerRef.current,",
  "            start: \"top top\",",
  "            end: \"+=420%\",",
  "            pin: pinnedContentRef.current,",
  "            pinSpacing: true,",
  "            scrub: 0.8,",
  "            anticipatePin: 1,",
  "            onUpdate: (self: { progress: number }) => {",
  "              setScrollProgress(self.progress);",
  "            }",
  "          }",
  "        }",
  "      );",
  "    });",
  "  }, containerRef, [effectiveReducedMotion, effectiveSupported]);",
  "",
  "  if (effectiveReducedMotion || !effectiveSupported) {",
  "    return (",
  "      <section id={config.id} data-scene-id={config.id} data-scene-index=\"2\">",
  "        <SignalFallback />",
  "      </section>",
  "    );",
  "  }",
  "",
  "  const apertureProgress = Math.min(1, scrollProgress / 0.12);",
  "  const alkotaOpacity = scrollProgress >= 0.94 ? (scrollProgress - 0.94) / 0.06 : 0;",
  "",
  "  return (",
  "    <section",
  "      ref={containerRef}",
  "      id={config.id}",
  "      data-scene-id={config.id}",
  "      data-scene-index=\"2\"",
  "      className=\"relative w-full bg-avorria-black\"",
  "    >",
  "      <div",
  "        ref={pinnedContentRef}",
  "        className=\"w-full h-screen h-[100dvh] relative overflow-hidden flex items-center justify-center\"",
  "      >",
  "        <SignalAperture progress={apertureProgress}>",
  "          <SignalCanvas",
  "            progress={scrollProgress}",
  "            onActiveProjectChange={setActiveProjectIndex}",
  "          />",
  "        </SignalAperture>",
  "",
  "        <SignalMetadataOverlay",
  "          activeIndex={activeProjectIndex}",
  "          progress={scrollProgress}",
  "        />",
  "",
  "        <AlkotaHandoffLayer opacity={alkotaOpacity} />",
  "",
  "        <div",
  "          className=\"absolute top-8 right-6 sm:right-12 font-mono text-[10px] sm:text-xs uppercase tracking-widest text-avorria-quiet z-20 pointer-events-none\"",
  "          aria-hidden=\"true\"",
  "        >",
  "          <span>02 / 18 // SIGNAL</span>",
  "        </div>",
  "      </div>",
  "    </section>",
  "  );",
  "}"
].join("\n"));

console.log("make_signal.js executed successfully");
