import type { SceneConfig, SceneId } from "@/types/scene";

export const HOMEPAGE_SCENES: SceneConfig[] = [
  {
    id: "scene-01-precision",
    index: 1,
    label: "01 / HERO — PRECISION AS POWER",
    chapter: "HERO",
    minHeight: "230vh",
    mobileHeight: "200svh",
    mobileSceneClass: "A",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "high",
    reducedMotionStrategy: "static",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_01_precision"
  },
  {
    id: "scene-selected-work-showcase" as any,
    index: 2,
    label: "02 / SELECTED WORK SHOWCASE",
    chapter: "SHOWCASE",
    minHeight: "580vh",
    mobileHeight: "530svh",
    mobileSceneClass: "C",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "high",
    reducedMotionStrategy: "simplified-motion",
    mobileStrategy: "mobileCinematic",
    analyticsName: "home_selected_work_showcase"
  },
  {
    id: "scene-capabilities-showcase" as any,
    index: 3,
    label: "03 / CAPABILITIES SHOWCASE",
    chapter: "CAPABILITY",
    minHeight: "360vh",
    mobileHeight: "300svh",
    mobileSceneClass: "B",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "static",
    mobileStrategy: "mobileCinematic",
    analyticsName: "home_capabilities_showcase"
  },
  {
    id: "scene-12-work",
    index: 4,
    label: "04 / WORK INDEX",
    chapter: "PORTFOLIO",
    minHeight: "auto",
    mobileHeight: "natural",
    mobileSceneClass: "A",
    bgMode: "black",
    pinningEligibility: false,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "static",
    mobileStrategy: "desktopCinematic",
    analyticsName: "scene_12_work"
  },
  {
    id: "scene-lab-teaser" as any,
    index: 5,
    label: "05 / AVORRIA LAB",
    chapter: "EXPERIMENTS",
    minHeight: "auto",
    mobileHeight: "natural",
    mobileSceneClass: "B",
    bgMode: "black",
    pinningEligibility: false,
    webglRequirement: false,
    mediaPriority: "low",
    reducedMotionStrategy: "static",
    mobileStrategy: "desktopCinematic",
    analyticsName: "scene_lab_teaser"
  },
  {
    id: "scene-15-manifesto",
    index: 6,
    label: "06 / MANIFESTO",
    chapter: "STATEMENT",
    minHeight: "140vh",
    mobileHeight: "130svh",
    mobileSceneClass: "A",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "low",
    reducedMotionStrategy: "static",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_15_manifesto"
  },
  {
    id: "scene-17-intelligence",
    index: 7,
    label: "07 / INTELLIGENCE",
    chapter: "EDITORIAL",
    minHeight: "auto",
    mobileHeight: "natural",
    mobileSceneClass: "A",
    bgMode: "black",
    pinningEligibility: false,
    webglRequirement: false,
    mediaPriority: "low",
    reducedMotionStrategy: "static",
    mobileStrategy: "desktopCinematic",
    analyticsName: "scene_17_intelligence"
  },
  {
    id: "scene-18-finale",
    index: 8,
    label: "08 / FINALE",
    chapter: "ENGAGEMENT",
    minHeight: "170vh",
    mobileHeight: "150svh",
    mobileSceneClass: "A",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "static",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_18_finale"
  }
];

export function getSceneConfig(id: SceneId): SceneConfig | undefined {
  return HOMEPAGE_SCENES.find((s) => s.id === id);
}
