import { SceneConfig, SceneId } from "@/types/scene";

export const HOMEPAGE_SCENES: SceneConfig[] = [
  {
    id: "scene-00-void",
    index: 0,
    label: "VOID",
    chapter: "PROLOGUE",
    minHeight: "100vh",
    mobileHeight: "90svh",
    mobileSceneClass: "A",
    bgMode: "black",
    pinningEligibility: false,
    webglRequirement: false,
    mediaPriority: "high",
    reducedMotionStrategy: "static",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_00_void"
  },
  {
    id: "scene-01-precision",
    index: 1,
    label: "PRECISION AS POWER",
    chapter: "STATEMENT",
    minHeight: "190vh",
    mobileHeight: "150svh",
    mobileSceneClass: "A",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "high",
    reducedMotionStrategy: "static",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_01_precision"
  },
  {
    id: "scene-02-signal",
    index: 2,
    label: "PROJECT SIGNAL",
    chapter: "GALLERY",
    minHeight: "380vh",
    mobileHeight: "240svh",
    mobileSceneClass: "C",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: true,
    mediaPriority: "high",
    reducedMotionStrategy: "simplified-motion",
    mobileStrategy: "mobileSimplified",
    analyticsName: "scene_02_signal"
  },
  {
    id: "scene-03-alkota",
    index: 3,
    label: "ALKOTA BIKES",
    chapter: "CASE STUDY",
    minHeight: "410vh",
    mobileHeight: "280svh",
    mobileSceneClass: "C",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: true,
    mediaPriority: "high",
    reducedMotionStrategy: "simplified-motion",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_03_alkota"
  },
  {
    id: "scene-04-breath",
    index: 4,
    label: "BREATH / MANIFESTO",
    chapter: "PHILOSOPHY",
    minHeight: "140vh",
    mobileHeight: "115svh",
    mobileSceneClass: "A",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "static",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_04_breath"
  },
  {
    id: "scene-05-careeros",
    index: 5,
    label: "CAREEROS",
    chapter: "CASE STUDY",
    minHeight: "340vh",
    mobileHeight: "270svh",
    mobileSceneClass: "C",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "high",
    reducedMotionStrategy: "simplified-motion",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_05_careeros"
  },
  {
    id: "scene-06-build",
    index: 6,
    label: "BUILD",
    chapter: "CAPABILITY",
    minHeight: "190vh",
    mobileHeight: "160svh",
    mobileSceneClass: "B",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "static",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_06_build"
  },
  {
    id: "scene-07-nestiq",
    index: 7,
    label: "NESTIQ",
    chapter: "CASE STUDY",
    minHeight: "310vh",
    mobileHeight: "250svh",
    mobileSceneClass: "C",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "simplified-motion",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_07_nestiq"
  },
  {
    id: "scene-08-search",
    index: 8,
    label: "SEARCH",
    chapter: "CAPABILITY",
    minHeight: "280vh",
    mobileHeight: "190svh",
    mobileSceneClass: "B",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "static",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_08_search"
  },
  {
    id: "scene-09-drawdown",
    index: 9,
    label: "DRAWDOWN.TRADING",
    chapter: "CASE STUDY",
    minHeight: "310vh",
    mobileHeight: "250svh",
    mobileSceneClass: "C",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "simplified-motion",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_09_drawdown"
  },
  {
    id: "scene-10-systems",
    index: 10,
    label: "SYSTEMS",
    chapter: "CAPABILITY",
    minHeight: "330vh",
    mobileHeight: "260svh",
    mobileSceneClass: "B",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "static",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_10_systems"
  },
  {
    id: "scene-11-entirefm",
    index: 11,
    label: "ENTIREFM",
    chapter: "CASE STUDY",
    minHeight: "250vh",
    mobileHeight: "200svh",
    mobileSceneClass: "B",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "simplified-motion",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_11_entirefm"
  },
  {
    id: "scene-12-work",
    index: 12,
    label: "SELECTED WORK",
    chapter: "ARCHIVE",
    minHeight: "auto",
    mobileHeight: "natural",
    mobileSceneClass: "A",
    bgMode: "black",
    pinningEligibility: false,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "static",
    mobileStrategy: "desktopCinematic",
    analyticsName: "scene_12_work"
  },
  {
    id: "scene-13-ogn",
    index: 13,
    label: "ONE GREAT NORTHERN",
    chapter: "CASE STUDY",
    minHeight: "200vh",
    mobileHeight: "170svh",
    mobileSceneClass: "B",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "simplified-motion",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_13_ogn"
  },
  {
    id: "scene-14-lab",
    index: 14,
    label: "AVORRIA LAB",
    chapter: "EXPERIMENTS",
    minHeight: "auto",
    mobileHeight: "natural",
    mobileSceneClass: "C",
    bgMode: "black",
    pinningEligibility: false,
    webglRequirement: true,
    mediaPriority: "low",
    reducedMotionStrategy: "simplified-motion",
    mobileStrategy: "mobileSimplified",
    analyticsName: "scene_14_lab"
  },
  {
    id: "scene-15-manifesto",
    index: 15,
    label: "MANIFESTO",
    chapter: "STATEMENT",
    minHeight: "190vh",
    mobileHeight: "170svh",
    mobileSceneClass: "A",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "low",
    reducedMotionStrategy: "static",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_15_manifesto"
  },
  {
    id: "scene-16-proof",
    index: 16,
    label: "PROOF",
    chapter: "EVIDENCE",
    minHeight: "auto",
    mobileHeight: "natural",
    mobileSceneClass: "A",
    bgMode: "black",
    pinningEligibility: false,
    webglRequirement: false,
    mediaPriority: "low",
    reducedMotionStrategy: "static",
    mobileStrategy: "desktopCinematic",
    analyticsName: "scene_16_proof"
  },
  {
    id: "scene-17-intelligence",
    index: 17,
    label: "INTELLIGENCE",
    chapter: "EDITORIAL",
    minHeight: "auto",
    mobileHeight: "natural",
    mobileSceneClass: "A",
    bgMode: "black",
    pinningEligibility: false,
    webglRequirement: false,
    mediaPriority: "low",
    reducedMotionStrategy: "static",
    mobileStrategy: "desktopCinematic",
    analyticsName: "scene_17_intelligence"
  },
  {
    id: "scene-18-finale",
    index: 18,
    label: "FINALE / START PROJECT",
    chapter: "ENGAGEMENT",
    minHeight: "200vh",
    mobileHeight: "170svh",
    mobileSceneClass: "A",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "static",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_18_finale"
  }
];

export function getSceneConfig(id: SceneId): SceneConfig | undefined {
  return HOMEPAGE_SCENES.find((s) => s.id === id);
}
