import { SceneConfig, SceneId } from "@/types/scene";

export const HOMEPAGE_SCENES: SceneConfig[] = [
  {
    id: "scene-01-precision",
    index: 1,
    label: "PRECISION AS POWER",
    chapter: "STATEMENT",
    minHeight: "170vh",
    mobileHeight: "140svh",
    mobileSceneClass: "A",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "high",
    reducedMotionStrategy: "static",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_01_precision"
  },
  {
    id: "scene-03-alkota",
    index: 3,
    label: "ALKOTA BIKES",
    chapter: "CLIENT WORK",
    minHeight: "260vh",
    mobileHeight: "210svh",
    mobileSceneClass: "C",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "high",
    reducedMotionStrategy: "simplified-motion",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_03_alkota"
  },
  {
    id: "scene-04-breath",
    index: 4,
    label: "BREATH / MANIFESTO",
    chapter: "PHILOSOPHY",
    minHeight: "120vh",
    mobileHeight: "110svh",
    mobileSceneClass: "A",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "static",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_04_breath"
  },
  {
    id: "scene-05-careeros",
    index: 5,
    label: "CAREEROS",
    chapter: "AVORRIA VENTURE",
    minHeight: "180vh",
    mobileHeight: "155svh",
    mobileSceneClass: "C",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "high",
    reducedMotionStrategy: "simplified-motion",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_05_careeros"
  },
  {
    id: "scene-06-build",
    index: 6,
    label: "BUILD",
    chapter: "CAPABILITY",
    minHeight: "150vh",
    mobileHeight: "135svh",
    mobileSceneClass: "B",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "static",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_06_build"
  },
  {
    id: "scene-07-nestiq",
    index: 7,
    label: "NESTIQ",
    chapter: "AVORRIA VENTURE",
    minHeight: "180vh",
    mobileHeight: "155svh",
    mobileSceneClass: "C",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "simplified-motion",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_07_nestiq"
  },
  {
    id: "scene-08-search",
    index: 8,
    label: "SEARCH",
    chapter: "CAPABILITY",
    minHeight: "150vh",
    mobileHeight: "135svh",
    mobileSceneClass: "B",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "static",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_08_search"
  },
  {
    id: "scene-09-drawdown",
    index: 9,
    label: "DRAWDOWN.TRADING",
    chapter: "AVORRIA VENTURE",
    minHeight: "180vh",
    mobileHeight: "155svh",
    mobileSceneClass: "C",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "simplified-motion",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_09_drawdown"
  },
  {
    id: "scene-10-systems",
    index: 10,
    label: "SYSTEMS",
    chapter: "CAPABILITY",
    minHeight: "160vh",
    mobileHeight: "140svh",
    mobileSceneClass: "B",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "static",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_10_systems"
  },
  {
    id: "scene-11-entirefm",
    index: 11,
    label: "ENTIREFM",
    chapter: "CLIENT WORK",
    minHeight: "170vh",
    mobileHeight: "145svh",
    mobileSceneClass: "B",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "simplified-motion",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_11_entirefm"
  },
  {
    id: "scene-12-work",
    index: 12,
    label: "SELECTED WORK",
    chapter: "ARCHIVE",
    minHeight: "auto",
    mobileHeight: "natural",
    mobileSceneClass: "A",
    bgMode: "black",
    pinningEligibility: false,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "static",
    mobileStrategy: "desktopCinematic",
    analyticsName: "scene_12_work"
  },
  {
    id: "scene-14-lab",
    index: 14,
    label: "AVORRIA LAB",
    chapter: "EXPERIMENTS",
    minHeight: "auto",
    mobileHeight: "natural",
    mobileSceneClass: "C",
    bgMode: "black",
    pinningEligibility: false,
    webglRequirement: true,
    mediaPriority: "low",
    reducedMotionStrategy: "simplified-motion",
    mobileStrategy: "mobileSimplified",
    analyticsName: "scene_14_lab"
  },
  {
    id: "scene-15-manifesto",
    index: 15,
    label: "MANIFESTO",
    chapter: "STATEMENT",
    minHeight: "170vh",
    mobileHeight: "150svh",
    mobileSceneClass: "A",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "low",
    reducedMotionStrategy: "static",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_15_manifesto"
  },
  {
    id: "scene-16-proof",
    index: 16,
    label: "PROOF",
    chapter: "EVIDENCE",
    minHeight: "auto",
    mobileHeight: "natural",
    mobileSceneClass: "A",
    bgMode: "black",
    pinningEligibility: false,
    webglRequirement: false,
    mediaPriority: "low",
    reducedMotionStrategy: "static",
    mobileStrategy: "desktopCinematic",
    analyticsName: "scene_16_proof"
  },
  {
    id: "scene-17-intelligence",
    index: 17,
    label: "INTELLIGENCE",
    chapter: "EDITORIAL",
    minHeight: "auto",
    mobileHeight: "natural",
    mobileSceneClass: "A",
    bgMode: "black",
    pinningEligibility: false,
    webglRequirement: false,
    mediaPriority: "low",
    reducedMotionStrategy: "static",
    mobileStrategy: "desktopCinematic",
    analyticsName: "scene_17_intelligence"
  },
  {
    id: "scene-18-finale",
    index: 18,
    label: "FINALE / START PROJECT",
    chapter: "ENGAGEMENT",
    minHeight: "190vh",
    mobileHeight: "160svh",
    mobileSceneClass: "A",
    bgMode: "black",
    pinningEligibility: true,
    webglRequirement: false,
    mediaPriority: "normal",
    reducedMotionStrategy: "static",
    mobileStrategy: "mobileCinematic",
    analyticsName: "scene_18_finale"
  }
];

export function getSceneConfig(id: SceneId): SceneConfig | undefined {
  return HOMEPAGE_SCENES.find((s) => s.id === id);
}
